apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deploy
  labels:
    app: nodejs-app
  annotations:
spec:
  selector:
    matchLabels:
      app: nodejs-app
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-app
        image: kiyange26773/nodejs:v1.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "64Mi"
            cpu: "10m"
          limits:
            memory: "256Mi"
            cpu: "500m"
